/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-02 05:35:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1679887448000L));
    _jspx_dependants.put("jar:file:/Users/ijin/Documents/workspace/5_server/semiProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    \n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta name =\"google-signin-client_id\" \n");
      out.write("    content=\"935814438564-8ocf3d4e2vsp790u21l0vctt9qahq9bj.apps.googleusercontent.com\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../resources/css/login.css\">\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.js\" \n");
      out.write("    integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\" \n");
      out.write("    crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("    <script src=\"https://kit.fontawesome.com/47910b9f42.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    \n");
      out.write("    <title>로그인</title>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div id=\"movieSourcing\">\n");
      out.write("        <div id=\"layout\">\n");
      out.write("            <div id=\"root\">\n");
      out.write("                <header>\n");
      out.write("                    <div>\n");
      out.write("                        <a href=\"#\" class=\"backpage\">\n");
      out.write("                            <i class=\"fa-solid fa-chevron-left\" id=\"backpageimg\"></i>\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                </header>\n");
      out.write("                <main id=\"contents\">\n");
      out.write("                    <section class=\"logintop\">\n");
      out.write("                        <span class=\"top\">로그인</span>\n");
      out.write("\n");
      out.write("                    </section>\n");
      out.write("                    <section class=\"loginbox\">\n");
      out.write("                        <div class=\"login\">\n");
      out.write("                            <div class=\"loginwrap\">\n");
      out.write("                                <form action=\"login\" method=\"POST\" name=\"login-form\" onsubmit=\"return loginValidate()\">\n");
      out.write("                                 <fieldset id=\"id-pw-area\">\n");
      out.write("                                        <span>아이디</span>\n");
      out.write("                                        <div class=\"id\">\n");
      out.write("                                            <input type=\"text\" id=\"id\"   name=\"id\" placeholder=\"아이디를 입력해주세요\">\n");
      out.write("                                        </div>\n");
      out.write("                                        <span>비밀번호</span>\n");
      out.write("                                        <div class=\"password\">\n");
      out.write("                                            <input type=\"password\" id=\"password\"  name=\"password\" placeholder=\"비밀번호를 입력해주세요\">\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"keepLogin\">\n");
      out.write("                                            <input type=\"checkbox\" name=\"keepLogin\">\n");
      out.write("                                            <label for=\"keepLogin\"><span>로그인 상태 유지</span></label>\n");
      out.write("                                        </div>\n");
      out.write("                                        <button id=\"nomalLogin\">\n");
      out.write("                                            <span>로그인</span>\n");
      out.write("                                        </button>\n");
      out.write("                                    </fieldset>\n");
      out.write("                                </form>\n");
      out.write("                               \n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"btnwrap\">\n");
      out.write("                                \n");
      out.write("                                <div id=\"kakaoLogin\">\n");
      out.write("                                    <div>\n");
      out.write("                                        <i class=\"fa-solid fa-comment\" id=\"kakaoImg\"></i>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div><span>카카오 로그인</span></div>\n");
      out.write("                                    <div></div>\n");
      out.write("                                </div>\n");
      out.write("                                <div id=\"googleLogin\">\n");
      out.write("                                    <div >\n");
      out.write("                                        <div class=\"googleBox\">\n");
      out.write("                                            <i class=\"fa-brands fa-google-plus-g\" id=\"googleImg\"></i>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div><span>구글 로그인</span></div>\n");
      out.write("                                    <div></div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"enderMenu\">\n");
      out.write("                                    <div>\n");
      out.write("                                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/signUp1\"><span>회원가입</span></a>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <a href=\"#\"><span>아이디</span></a>\n");
      out.write("                                        <span> |</span>\n");
      out.write("                                        <a href=\"#\"><span>비밀번호찾기</span></a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                            \n");
      out.write("                        </div>\n");
      out.write("                    </section>\n");
      out.write("                    <section class=\"under\">\n");
      out.write("\n");
      out.write("                    </section>\n");
      out.write("                    <button id=\"logout\">로그아웃</button>\n");
      out.write("                   \n");
      out.write("                </main>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script src=\"../resources/js/login.js\"></script>\n");
      out.write("    \n");
      out.write("    <script src=\"https://developers.kakao.com/sdk/js/kakao.js\"></script>\n");
      out.write("    <script>    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("        Kakao.init('b1d9a2e7a04258418caf62b1eca84f41');\n");
      out.write("        console.log(Kakao.isInitialized()); \n");
      out.write("\n");
      out.write("        document.getElementById(\"kakaoLogin\")\n");
      out.write("        .addEventListener(\"click\", function kakaoLogin() {\n");
      out.write("            Kakao.Auth.login({\n");
      out.write("            success: function (response) {\n");
      out.write("                Kakao.API.request({\n");
      out.write("                url: '/v2/user/me',\n");
      out.write("                success: function (response) {\n");
      out.write("                    console.log(response)\n");
      out.write("                },\n");
      out.write("                fail: function (error) {\n");
      out.write("                    console.log(error)\n");
      out.write("                },\n");
      out.write("                })\n");
      out.write("            },\n");
      out.write("            fail: function (error) {\n");
      out.write("                console.log(error)\n");
      out.write("            },\n");
      out.write("            })\n");
      out.write("        })\n");
      out.write("        document.getElementById(\"logout\")\n");
      out.write("        .addEventListener(\"click\", function kakaoLogout() {\n");
      out.write("            if (Kakao.Auth.getAccessToken()) {\n");
      out.write("            Kakao.API.request({\n");
      out.write("                url: '/v1/user/unlink',\n");
      out.write("                success: function (response) {\n");
      out.write("                    console.log(response)\n");
      out.write("                },\n");
      out.write("                fail: function (error) {\n");
      out.write("                console.log(error)\n");
      out.write("                },\n");
      out.write("            })\n");
      out.write("            Kakao.Auth.setAccessToken(undefined)\n");
      out.write("            }\n");
      out.write("        }  )\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        function init() {\n");
      out.write("            gapi.load('auth2', function() {\n");
      out.write("                gapi.auth2.init();\n");
      out.write("                options = new gapi.auth2.SigninOptionsBuilder();\n");
      out.write("                options.setPrompt('select_account');\n");
      out.write("                options.setScope('email profile openid https://www.googleapis.com/auth/user.birthday.read');\n");
      out.write("                gapi.auth2.getAuthInstance().attachClickHandler('googleLogin', options, onSignIn, onSignInFailure);\n");
      out.write("            })\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function onSignIn(googleUser) {\n");
      out.write("            var access_token = googleUser.getAuthResponse().access_token\n");
      out.write("            $.ajax({\n");
      out.write("                url: 'https://people.googleapis.com/v1/people/me'\n");
      out.write("                 , data: {personFields:'birthdays', key:'AIzaSyAR3Snhp3uGfBQ0Sw_Bfa82gwbpqr_cFRE', 'access_token': access_token}\n");
      out.write("                , method:'GET'\n");
      out.write("            })\n");
      out.write("            .done(function(e){\n");
      out.write("               var profile = googleUser.getBasicProfile();\n");
      out.write("                console.log(profile)\n");
      out.write("            })\n");
      out.write("            .fail(function(e){\n");
      out.write("                console.log(e);\n");
      out.write("            })\n");
      out.write("        }\n");
      out.write("        function onSignInFailure(t){		\n");
      out.write("            console.log(t);\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    <script src=\"https://apis.google.com/js/platform.js?onload=init\" async defer></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
